# Generated by Django 2.2.5 on 2019-10-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderModerateDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDescription', models.TextField(verbose_name='Потроха закупки')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrderModerateTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=3, verbose_name='Id')),
                ('orderTitle', models.CharField(max_length=50, verbose_name='Название закупки')),
            ],
        ),
    ]
