# Generated by Django 2.2.5 on 2019-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('proc', models.IntegerField()),
                ('typeMin', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
    ]
